[profile.default]
src = "src"
out = "out"
libs = ['node_modules',"lib"]
remappings = ['@chainlink/contracts/=lib/chainlink/contracts/', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/', '@solmate=lib/solmate/src/']

[etherscan]
sepolia = {key = "${API_KEY_SEP}"}

[rpc_endpoints]
sepolia = "${RPC_URL_SEP}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
